-- Observed-population sampling via /who.
--
-- A user-triggered scan issues one C_FriendList.SendWho, then captures the
-- returned roster on WHO_LIST_UPDATE and folds race/class/level counts into a
-- stored sample. This mirrors how the AH Scanner captures a listings snapshot,
-- but for the realm's player directory rather than the Auction House.
--
-- Two Blizzard constraints shape the design (see warcraft.wiki.gg):
--   * SendWho must originate from a HARDWARE EVENT (a real key/mouse action)
--     and is rate-limited server-side; requests sent too fast are silently
--     dropped. So a scan is only ever kicked off from a button/slash press,
--     never from a timer, and we add a small client-side cooldown on top.
--   * Small result sets print to chat and never reach GetWhoInfo unless
--     SetWhoToUi(true) routes them into the API. We enable it around a scan
--     and restore the default afterward so normal /who still prints to chat.
--
-- A /who is a SAMPLE of currently-visible online players (capped ~50 by the
-- server), never a realm census. The UI labels it "Observed Population" and
-- counts sightings, not unique characters.

local ML = MarketLens
local Pop = ML.Population
local U = ML.Util
local D = ML.Data

local COOLDOWN = 6      -- seconds we enforce between our own SendWho calls
local SCAN_CAP = 1000   -- retained samples per realm (also purged by retention)

Pop.pending = false
Pop.lastSend = 0
Pop.COOLDOWN = COOLDOWN

-- API shims: C_FriendList (Classic/Retail) with legacy global fallbacks

local function sendWho(filter)
    if C_FriendList and C_FriendList.SendWho then
        C_FriendList.SendWho(filter)
    elseif SendWho then
        SendWho(filter)
    end
end

local function setWhoToUi(on)
    if C_FriendList and C_FriendList.SetWhoToUi then
        C_FriendList.SetWhoToUi(on)
    elseif SetWhoToUI then
        SetWhoToUI(on)
    end
end

local function numResults()
    if C_FriendList and C_FriendList.GetNumWhoResults then
        return C_FriendList.GetNumWhoResults()
    elseif GetNumWhoResults then
        return GetNumWhoResults()
    end
    return 0, 0
end

local function whoInfo(i)
    if C_FriendList and C_FriendList.GetWhoInfo then
        return C_FriendList.GetWhoInfo(i)
    elseif GetWhoInfo then
        -- Legacy positional return -> normalize to the modern table shape.
        local name, guild, level, race, class, zone, classFileName, sex = GetWhoInfo(i)
        return { fullName = name, fullGuildName = guild, level = level,
                 raceStr = race, classStr = class, area = zone,
                 filename = classFileName, gender = sex }
    end
end

local function trim(s)
    return tostring(s or ""):gsub("^%s+", ""):gsub("%s+$", "")
end

local function identity(info)
    local fullName = trim(info.fullName)
    if fullName == "" then return nil end
    local name, realm = fullName:match("^([^-]+)%-(.+)$")
    name = trim(name or fullName)
    realm = trim(realm or GetRealmName() or "UnknownRealm")
    if name == "" then return nil end
    local normalizedRealm = realm:lower():gsub("[%s']", "")
    local key = ML:GameFlavor() .. ":" .. normalizedRealm .. ":" .. name:lower()
    return key, name .. "-" .. realm, name, realm
end

-- Class-mix -> inferred crafting demand
--
-- Heuristic weights: which crafting markets a class buys from. Every raiding
-- class demands Enchanting (chants), Alchemy (flasks/potions) and gems
-- (Jewelcrafting); the differentiator is the armor-type profession that makes
-- their gear (plate=Blacksmithing, mail/leather=Leatherworking, cloth=Tailoring).
-- Keys are locale-independent class tokens (WhoInfo.filename); values map to
-- ML.Data.Professions keys. This is a demand HINT, never observed sales.
--
-- The gear/armor-type slot used to be a flat guess (crafting profession = 3,
-- generic "Gear" = 2 -- i.e. "60% of this class's gear demand is craftable").
-- D.GearCraftShare (Data/GearCoverageGen.lua, generated by
-- tools/build-item-sources.js from Blizzard's own item data) says what that
-- split actually is: only ~4-7% of a given armor type's items are a known
-- player recipe, the rest is drops/quests/vendor/other that no profession can
-- supply. GEAR_BUDGET keeps the combined weight the same as the old 3+2 total
-- so this slot stays comparable in scale to the unrelated flat weights below
-- (Enchanting/Alchemy/Jewelcrafting/Engineering), just honestly split.
local GEAR_BUDGET = 5
-- Fallback shares if Data/GearCoverageGen.lua didn't load (e.g. an old client
-- cache) -- the values generated as of build 2.5.6.69546; kept in sync by
-- re-running tools/build-item-sources.js.
local DEFAULT_GEAR_SHARE = { Blacksmithing = 0.0390, Leatherworking = 0.0545, Tailoring = 0.0671 }

local function gearShare(profession)
    local share = D.GearCraftShare and D.GearCraftShare[profession]
    return share or DEFAULT_GEAR_SHARE[profession] or 0
end

-- gearSlot(profession) returns { [profession] = craftable share, Gear = rest },
-- both scaled off GEAR_BUDGET so the total matches every other class's.
local function gearSlot(profession)
    local share = gearShare(profession)
    return { [profession] = GEAR_BUDGET * share, Gear = GEAR_BUDGET * (1 - share) }
end

local function affinity(profession, extra)
    local aff = gearSlot(profession)
    for prof, w in pairs(extra) do aff[prof] = w end
    return aff
end

Pop.ClassAffinity = {
    WARRIOR = affinity("Blacksmithing", { Enchanting = 2, Alchemy = 1, Jewelcrafting = 1 }),
    PALADIN = affinity("Blacksmithing", { Enchanting = 2, Alchemy = 1, Jewelcrafting = 1 }),
    HUNTER  = affinity("Leatherworking", { Engineering = 1, Enchanting = 1, Alchemy = 1 }),
    ROGUE   = affinity("Leatherworking", { Alchemy = 2, Enchanting = 1 }),
    SHAMAN  = affinity("Leatherworking", { Enchanting = 1, Jewelcrafting = 1, Alchemy = 1 }),
    DRUID   = affinity("Leatherworking", { Alchemy = 1, Enchanting = 1 }),
    PRIEST  = affinity("Tailoring", { Enchanting = 2, Alchemy = 1, Jewelcrafting = 1 }),
    MAGE    = affinity("Tailoring", { Enchanting = 2, Jewelcrafting = 1, Alchemy = 1 }),
    WARLOCK = affinity("Tailoring", { Enchanting = 2, Alchemy = 1 }),
    -- Retail-only classes. Harmless on Classic/TBC where these tokens never
    -- appear in /who results. Armor-type -> crafter follows modern rules
    -- (plate=Blacksmithing, leather & mail=Leatherworking, cloth=Tailoring).
    DEATHKNIGHT = affinity("Blacksmithing", { Enchanting = 2, Alchemy = 1, Jewelcrafting = 1 }),
    MONK        = affinity("Leatherworking", { Alchemy = 1, Enchanting = 1, Jewelcrafting = 1 }),
    DEMONHUNTER = affinity("Leatherworking", { Alchemy = 2, Enchanting = 1 }),
    EVOKER      = affinity("Leatherworking", { Enchanting = 2, Alchemy = 1, Jewelcrafting = 1 }),
}

-- Rank professions by summed class affinity across an aggregate's class mix.
-- Scores are normalized 0-100 relative to the top profession. Returns a list
-- of { prof=, weight=, score= } sorted by weight, or {} if no class data.
function Pop:ProfessionDemand(agg)
    if not agg or not agg.classes then return {} end
    local weights = {}
    for token, n in pairs(agg.classes) do
        local aff = self.ClassAffinity[token]
        if aff then
            for prof, w in pairs(aff) do
                weights[prof] = (weights[prof] or 0) + w * n
            end
        end
    end

    local max = 0
    for _, w in pairs(weights) do if w > max then max = w end end

    local out = {}
    for prof, w in pairs(weights) do
        out[#out + 1] = {
            prof   = prof,
            weight = w,
            score  = max > 0 and U.Round(w / max * 100) or 0,
        }
    end
    table.sort(out, function(a, b) return a.weight > b.weight end)
    return out
end

-- Kick off one population sample. MUST be reached from a hardware event
-- (a button or slash-command press) or Blizzard drops the SendWho. `tag`
-- rides along to POP_SCAN_COMPLETE so a caller (the census) can recognize its
-- own result. Returns true when the query was actually sent.
function Pop:Scan(filter, tag)
    filter = filter and filter:gsub("^%s+", ""):gsub("%s+$", "") or ""
    if filter == "" then
        local maxL = (GetMaxPlayerLevel and GetMaxPlayerLevel()) or 70
        filter = "1-" .. maxL
    end

    local now = GetTime()
    -- A still-pending scan within the cooldown is genuinely in flight; once the
    -- cooldown has elapsed with no WHO_LIST_UPDATE, treat it as dropped by the
    -- server (SendWho throttling) and let this press start a fresh one.
    if self.pending and now - self.lastSend < COOLDOWN then
        ML:Print("Population scan already in progress...")
        return false
    end
    if now - self.lastSend < COOLDOWN then
        ML:Print("Population scans are throttled \226\128\148 wait a few seconds and retry.")
        return false
    end

    self.pending = true
    self.pendingFilter = filter
    self.pendingTag = tag
    local store = self:Store()
    self.pendingSweepID = store.activeSweepID
    self.lastSend = now
    setWhoToUi(true)
    -- The census prints its own one-line step summary instead.
    if tag ~= "census" then ML:Print("Population scan: |cffffffff%s|r ...", filter) end
    ML:Fire("POP_SCAN_START", filter)
    sendWho(filter)
    return true
end

-- Seconds until the client-side cooldown lets another SendWho through.
function Pop:CooldownRemaining()
    return math.max(COOLDOWN - (GetTime() - self.lastSend), 0)
end

-- Fold the current WHO_LIST results into a stored sample. Called on
-- WHO_LIST_UPDATE, but only acts on a scan we started (self.pending).
function Pop:Capture()
    if not self.pending then return end
    self.pending = false
    setWhoToUi(false) -- restore default so manual /who prints to chat again

    local shown, total = numResults()
    shown = shown or 0

    local classes, races, roster = {}, {}, {}
    local observed = 0
    for i = 1, shown do
        local info = whoInfo(i)
        if info then
            local token = info.filename or info.classStr or "UNKNOWN"
            local race  = info.raceStr or "Unknown"
            classes[token] = (classes[token] or 0) + 1
            races[race]    = (races[race] or 0) + 1
            observed = observed + 1
            local key, fullName, name, realm = identity(info)
            if key and not roster[key] then
                roster[key] = {
                    key = key, fullName = fullName, name = name, realm = realm,
                    guild = info.fullGuildName or "", level = info.level or 0,
                    race = race, class = info.classStr or token,
                    classFile = token, zone = info.area or "",
                }
            end
        end
    end

    local sample = {
        t        = time(),
        faction  = UnitFactionGroup and UnitFactionGroup("player") or "Neutral",
        filter   = self.pendingFilter,
        observed = observed,
        total    = total or observed, -- server-reported online matching the filter
        classes  = classes,
        races    = races,
    }
    local unique = self:Record(sample, roster)
    self:RecordSweepQuery(sample, roster, self.pendingSweepID)
    self.pendingSweepID = nil
    local tag = self.pendingTag
    self.pendingTag = nil
    -- The server's "total" is capped alongside the list, so it never says how
    -- many players really matched; flag the cap instead of quoting it.
    if tag ~= "census" then
        ML:Print("%s: %d result(s)%s; recorded %d unique character(s).",
            sample.filter or "", observed,
            self:IsCapped(observed) and " |cffff8040(capped \226\128\148 more exist)|r" or "", unique)
    end
    ML:Fire("POP_SCAN_COMPLETE", sample, tag)
end

function Pop:Store()
    local realm = ML.realm
    realm.population = realm.population or { samples = {}, characters = {} }
    realm.population.samples = realm.population.samples or {}
    realm.population.characters = realm.population.characters or {}
    realm.population.sweeps = realm.population.sweeps or {}
    return realm.population
end

-- A sweep is an explicitly bounded collection session. It does not claim
-- coverage merely because queries were run: the collector closes it as either
-- complete or partial. Every query and its deduplicated character locations
-- are retained independently of the lifetime/latest-known character table.
function Pop:StartSweep(label, quiet)
    local store = self:Store()
    if store.activeSweepID then
        self:FinishSweep("partial")
        ML:Print("Previous active sweep was closed as partial.")
    end
    store.nextSweepSeq = (store.nextSweepSeq or 0) + 1
    local started = time()
    local id = tostring(started) .. "-" .. tostring(store.nextSweepSeq)
    store.sweeps[id] = {
        id = id, startedAt = started, completedAt = 0, status = "active",
        label = trim(label), faction = UnitFactionGroup and UnitFactionGroup("player") or "Neutral",
        queries = {}, observations = {},
    }
    store.activeSweepID = id
    if not quiet then
        ML:Print("Started population sweep |cffffffff%s|r. Run /ml who filters, then /ml sweep complete or /ml sweep partial.", id)
    end
    ML:Fire("POP_SWEEP_CHANGED", store.sweeps[id])
    return id
end

function Pop:FinishSweep(status)
    local store = self:Store()
    local id = store.activeSweepID
    local sweep = id and store.sweeps[id]
    if not sweep then
        ML:Print("No population sweep is active.")
        return nil
    end
    status = status == "complete" and "complete" or "partial"
    sweep.status = status
    sweep.completedAt = time()
    store.activeSweepID = nil
    local chars = 0
    for _ in pairs(sweep.observations or {}) do chars = chars + 1 end
    ML:Print("Closed sweep |cffffffff%s|r as %s: %d queries, %d unique characters.",
        id, status, #(sweep.queries or {}), chars)
    ML:Fire("POP_SWEEP_CHANGED", sweep)
    return sweep
end

function Pop:SweepStatus()
    local store = self:Store()
    local sweep = store.activeSweepID and store.sweeps[store.activeSweepID]
    if not sweep then
        ML:Print("No population sweep is active.")
        return nil
    end
    local chars, capped = 0, 0
    for _ in pairs(sweep.observations or {}) do chars = chars + 1 end
    for _, q in ipairs(sweep.queries or {}) do if q.capped then capped = capped + 1 end end
    ML:Print("Sweep %s: %d queries, %d unique characters, %d capped queries.",
        sweep.id, #(sweep.queries or {}), chars, capped)
    return sweep
end

function Pop:RecordSweepQuery(sample, roster, sweepID)
    if not sweepID then return end
    local store = self:Store()
    local sweep = store.sweeps[sweepID]
    if not sweep or sweep.status ~= "active" then return end
    sweep.queries = sweep.queries or {}
    sweep.observations = sweep.observations or {}
    local queryIndex = #sweep.queries + 1
    sweep.queries[queryIndex] = {
        index = queryIndex, t = sample.t, filter = sample.filter,
        observed = sample.observed or 0, total = sample.total or sample.observed or 0,
        capped = (sample.total or 0) > (sample.observed or 0) or self:IsCapped(sample.observed),
    }
    -- Every character this query returned (not just the latest sighting), so
    -- overlap between queries can be measured: that is what capture-recapture
    -- estimates, and the test of whether /who returns a random 50, rest on.
    local keys = {}
    for key in pairs(roster or {}) do keys[#keys + 1] = key end
    sweep.queries[queryIndex].keys = keys
    for key, seen in pairs(roster or {}) do
        sweep.observations[key] = {
            key = key, queryIndex = queryIndex, observedAt = sample.t,
            zone = seen.zone or "", level = seen.level or 0,
            classFile = seen.classFile or "", race = seen.race or "",
        }
    end
    ML:Fire("POP_SWEEP_CHANGED", sweep)
end

function Pop:Record(sample, roster)
    local store = self:Store()
    U.PushCapped(store.samples, sample, SCAN_CAP)
    store.lastScan = sample.t
    local day = math.floor(sample.t / 86400)
    local unique = 0
    for key, seen in pairs(roster or {}) do
        unique = unique + 1
        local c = store.characters[key]
        if not c then
            c = { key = key, firstSeen = sample.t, seenCount = 0, days = {} }
            store.characters[key] = c
        end
        c.fullName, c.name, c.realm = seen.fullName, seen.name, seen.realm
        c.guild, c.level, c.race = seen.guild, seen.level, seen.race
        c.class, c.classFile, c.zone = seen.class, seen.classFile, seen.zone
        c.firstSeen = math.min(c.firstSeen or sample.t, sample.t)
        c.lastSeen = math.max(c.lastSeen or 0, sample.t)
        c.seenCount = (c.seenCount or 0) + 1
        c.days = c.days or {}
        local d = c.days[day] or { count = 0, firstSeen = sample.t, lastSeen = sample.t }
        d.count = (d.count or 0) + 1
        d.firstSeen = math.min(d.firstSeen or sample.t, sample.t)
        d.lastSeen = math.max(d.lastSeen or 0, sample.t)
        c.days[day] = d
    end
    self:Purge()
    return unique
end

-- Drop old samples and daily observations. Lifetime character records remain so
-- returning/new-to-dataset status survives beyond the rolling analytics window.
function Pop:Purge()
    local store = ML.realm.population
    if not store or not store.samples then return 0 end
    local days = ML.db.settings.populationRetentionDays or 35
    local cutoff = time() - days * 86400
    local cutoffDay = math.floor(cutoff / 86400)
    local kept, removed = {}, 0
    for _, s in ipairs(store.samples) do
        if s.t >= cutoff then kept[#kept + 1] = s else removed = removed + 1 end
    end
    store.samples = kept
    for _, c in pairs(store.characters or {}) do
        for day in pairs(c.days or {}) do
            if (tonumber(day) or 0) < cutoffDay then c.days[day] = nil end
        end
    end
    for id, sweep in pairs(store.sweeps or {}) do
        local ended = sweep.completedAt or sweep.startedAt or 0
        if sweep.status ~= "active" and ended < cutoff then store.sweeps[id] = nil end
    end
    return removed
end

-- Distinct zone names seen across every captured character in this realm
-- bucket, with a count. Plain eyeballing of the roster to spot new/renamed
-- zones (e.g. a fresh beta) instead of guessing against remembered zone lists.
function Pop:DumpZones()
    local store = ML.realm and ML.realm.population
    local characters = store and store.characters
    if not characters or not next(characters) then
        ML:Print("No population data yet -- run /ml who first.")
        return
    end
    local counts = {}
    for _, c in pairs(characters) do
        local zone = c.zone
        if zone and zone ~= "" then
            counts[zone] = (counts[zone] or 0) + 1
        end
    end
    local zones = {}
    for zone in pairs(counts) do zones[#zones + 1] = zone end
    table.sort(zones)
    ML:Print("%d distinct zone(s) captured for %s:", #zones, ML:RealmKey())
    for _, zone in ipairs(zones) do
        ML:Print("  %s (%d)", zone, counts[zone])
    end
end

-- Unique-character metrics from the rolling observation window. These are
-- characters, not Battle.net accounts; /who cannot associate alts or renames.
function Pop:CharacterStats()
    local store = self:Store()
    local today = math.floor(time() / 86400)
    local stats = { lifetime = 0, today = 0, week = 0, month = 0,
                    newWeek = 0, returningWeek = 0, active3 = 0 }
    local weekStart, monthStart = today - 6, today - 29
    for _, c in pairs(store.characters) do
        stats.lifetime = stats.lifetime + 1
        local inToday, inWeek, inMonth, monthDays = false, false, false, 0
        for day in pairs(c.days or {}) do
            day = tonumber(day) or 0
            if day == today then inToday = true end
            if day >= weekStart then inWeek = true end
            if day >= monthStart then inMonth, monthDays = true, monthDays + 1 end
        end
        if inToday then stats.today = stats.today + 1 end
        if inWeek then
            stats.week = stats.week + 1
            if (c.firstSeen or 0) >= weekStart * 86400 then
                stats.newWeek = stats.newWeek + 1
            else
                stats.returningWeek = stats.returningWeek + 1
            end
        end
        if inMonth then stats.month = stats.month + 1 end
        if monthDays >= 3 then stats.active3 = stats.active3 + 1 end
    end
    stats.returningRate = stats.week > 0 and U.Round(stats.returningWeek / stats.week * 100) or 0
    return stats
end

-- Sum class/race sightings across samples within `secondsAgo` (nil = all
-- retained). Returns { classes=, races=, observed=, samples=, lastScan= } or
-- nil when nothing has been sampled yet.
function Pop:Aggregate(secondsAgo)
    local store = ML.realm.population
    if not store or not store.samples then return nil end
    local cutoff = secondsAgo and (time() - secondsAgo) or 0

    local classes, races = {}, {}
    local observed, samples, lastScan = 0, 0, nil
    for _, s in ipairs(store.samples) do
        if s.t >= cutoff then
            samples  = samples + 1
            observed = observed + (s.observed or 0)
            lastScan = s.t
            for k, v in pairs(s.classes or {}) do classes[k] = (classes[k] or 0) + v end
            for k, v in pairs(s.races or {})   do races[k]   = (races[k] or 0) + v end
        end
    end
    if samples == 0 then return nil end
    return { classes = classes, races = races, observed = observed,
             samples = samples, lastScan = lastScan }
end

function Pop:Latest()
    local store = ML.realm.population
    if not store or not store.samples or #store.samples == 0 then return nil end
    return store.samples[#store.samples]
end

-- Blizzard refused a protected call we made ("Interface action failed because
-- of an AddOn"). Name the function instead of leaving a bare error, and if it
-- was our /who, release the pending scan so the caller can retry at once.
function Pop:OnActionBlocked(event, addon, func)
    if addon ~= ML.ADDON then return end
    ML:Print("|cffff4040Blizzard blocked %s()|r (%s).", tostring(func), event)
    if self.pending then
        self.pending = false
        setWhoToUi(false)
        local tag = self.pendingTag
        self.pendingTag, self.pendingSweepID = nil, nil
        -- A census recovers on its own (chat mode); only guide manual scans.
        if tag ~= "census" then
            ML:Print("That /who was not sent. Type it as |cffffff00/ml who <filter>|r in chat instead.")
        end
        ML:Fire("POP_SCAN_FAILED", self.pendingFilter, tag)
    end
end

local frame = CreateFrame("Frame")
frame:RegisterEvent("WHO_LIST_UPDATE")
frame:RegisterEvent("ADDON_ACTION_FORBIDDEN")
frame:RegisterEvent("ADDON_ACTION_BLOCKED")
frame:SetScript("OnEvent", function(_, event, ...)
    if event == "WHO_LIST_UPDATE" then
        Pop:Capture()
    else
        Pop:OnActionBlocked(event, ...)
    end
end)

function Pop:Init()
    -- Nothing to warm up; the WHO_LIST_UPDATE handler is live from file load.
end
