
-- GENERATED by tools/build-item-sources.js -- do not edit by hand.
-- Source: wago.tools DB2 export, build 2.5.6.69546 (Item.db2 class/subclass census).
--
-- What fraction of each armor-crafting profession's addressable gear is an
-- actual player recipe (Data/ItemSourcesGen.lua), vs. drops/quests/vendor/other
-- that no profession supplies. Population/WhoScan.lua uses this to split each
-- class's flat generic-Gear demand weight into a profession-attributed share
-- and a true unattributed-Gear share, instead of a guessed constant.
--
--   Tailoring:      257 / 3829 cloth armor items = 6.7%
--   Leatherworking: 301 / 5525 leather+mail armor items = 5.4%
--   Blacksmithing:  251 / 6444 plate armor + weapon items = 3.9%

local ML = MarketLens
local D = ML.Data

D.GearCraftShare = {
    Tailoring = 0.0671,
    Leatherworking = 0.0545,
    Blacksmithing = 0.0390,
}
